version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  signup-service:
    build: ./signupservice
    ports: #HOST_PORT:CONTAINER_PORT
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092

  mariadb-db:
    image: mariadb/server:10.3
    environment:
      MYSQL_ROOT_PASSWORD: mypass
    restart: always
    ports:
      - "3306:3306"

  persistence-service:
    build: ./persistenceservice
    depends_on:
      - kafka
      - mariadb-db
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
      JAVA_OPTS: -Dsignup.datasource.url=jdbc:mariadb://mariadb-db:3306/ -Dsignup.datasource.password=mypass