signup:
  topic: signup-topic
  topic-dlt: signup-topic.DLT
  datasource:
    url: jdbc:mariadb://localhost:3306/
    username: root
    password: mypass
    minimumIdle: 1
    maximumPoolSize: 3
    poolName: apex
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springjdbc
    username: guest_user
    password: guest_password
