signup:
  topic: signup-topic
  topic-dlt: signup-topic.DLT
  datasource:
    url: jdbc:mariadb://localhost:3306/
    username: root
    password: mypass
    minimumIdle: 1
    maximumPoolSize: 3
    poolName: apex
server:
  port: 8081
spring:
  kafka:
    bootstrap-servers: localhost:9092